[tool.black]
line-length = 100

[project]
name = "tiangong-ai-vllm"
version = "0.1.0"
description = "TianGong AI vLLM serving presets"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
	"vllm",
	"modelscope",
]

[dependency-groups]
dev = [
	"black",
]
